### PR TITLE
Comments + other UX improvements

### PR DESCRIPTION
**Pull request by micahlt**
In this PR: 

- Optimized images
- Actions workflow to generate APKs
- Open user profiles from feed events
- View user comments
- View project comments
- Upgraded dependencies
- Added a link to the [Privacy Policy](https://itchy.micahlindley.com/privacy.html)
- Handle `404` and `500` errors on users and projects
- Add message location details (e.g., "on your profile", "in Elders of Scratch")

[📦 Nightly APK (zipped)](https://github.com/Scratch-Client-4/itchy-ionic/suites/5459478272/artifacts/173676813)

### CODE REVIEW

**Comment by locness3** [comment]
Where do I get the APK?

**Comment by micahlt** [comment]
> Where do I get the APK?

Lol, I already put it in the PR.  It's zipped for compression.  However, you could always download it directly from the last GitHub Actions run.

**Comment by micahlt** [comment]
Okay, I'm done with my additions to this PR.  The nightly APK has been updated in the original comment, so it's ready for testing.  @locness3 waiting on your review.

**Comment by locness3** [comment]
Screenshot_20220228-003439
In my opinion, the Share icon is not fitting, should be closer to the material design version, but also these buttons should in the top-right of the titlebar, at least for the share button. (I know this is not the most usable, but it is what I'm used to seeing on Android.) You might want to add the comments and other future buttons (follow) below the username and join date, on user pages, and below or above the description in project pages
The comment view looks good on the design side to me, although it seems like it doesn't go past the n first comments, and they don't load on projects with disabled comments, or maybe with too many comments (Paper Minecraft).
I won't review the Privacy Policy itself, however it should be stated that the user agrees with the privacy policy by signing in (or just using the app, perhaps including it in a "welcome wizard" in the near future).
Congrats on getting an automated build working.

**Comment by locness3** [comment]
Wait, turns out the Share icon is actually Open in browser. Then it would better fit in a "vertical three dots" menu in the top-right of the title bar, without an icon.

**Comment by micahlt** [comment]
> In my opinion, the Share icon is not fitting, should be closer to the material design version

You're talking about the Open in Browser button.

> it would better fit in a "vertical three dots" menu in the top-right of the title bar

You're probably right about that according to the Material Design guidelines.  Personally I found placing it under the FAB to be more ergonomic, but I'll file an issue about that and we'll look into it further.  

> it should be stated that the user agrees with the privacy policy by signing in

True - I'll change this.

> it doesn't go past the n first comments

You're correct - more than 1 page of comments has not yet been implemented.  Eventually I'll probably use an `ion-infinite-scroll` component to load more.  

> they don't load on projects with disabled comments

Ah yeah, this is something I'll also have to file an issue about.  Not sure what comment endpoints return when comments are disabled.  

> a "welcome wizard" in the near future

Totally - that's something I'd love to add in the future.  I actually already have some UI concepts.

> add the comments and other future buttons (follow) below the username and join date

Hmm... can't say I'm a big fan of that idea.  Yes, it's more easily discoverable, but it pushes content even further below the fold.  FABs are called Floating **Action** Button for a reason - anything interactive or that's done often can be placed in one.  See the [Material Guidelines article](https://material.io/components/buttons-floating-action-button#types-of-transitions).

> Congrats on getting an automated build working

Thank you!  Glad to get this project into a more manageable state.

**Comment by micahlt** [comment]
All right - merging this now.  The above issues have been filed and will be worked on post-merge.

**Comment by locness3** [comment]
> You're talking about the Open in Browser button.

yes, I made another comment.

**Pull request merged**
