### PR TITLE
Feature updates and bugfixes

### PR DESCRIPTION
**Pull request by micahlt**
- Added an unread message badge to the tab bar
- Added an "Open profile" button in Settings
- Fixed handling Intents on Android
- Added infinite scroll to messages

### CODE REVIEW

**Comment by locness3** [comment]
Infinite scroll? Think about it again.

**Review by locness3 — APPROVED** [review]
otherwise lgtm.

**Comment by micahlt** [comment]
> Infinite scroll? Think about it again.

What are you talking about?

**Comment by locness3** [comment]
infinite scroll is a bad UX from a user point of view, but that's mostly when it's about finding what you need to; it can fit here for going through older things.

**Comment by locness3** [comment]
Also I'm sorry for my recent inactivity on this project, to be honest i kinda forgot about it when i had time. (But please move the repo to your personal profile)

**Comment by micahlt** [comment]
@locness3 What's the benefit of moving the repo to my profile?

**Comment by locness3** [comment]
Ending Scratch Client 4

**Comment by micahlt** [comment]
@locness3 But why do we need to end Scratch Client 4?

**Comment by locness3** [comment]
It's not really anything anymore... it used to be an actual software project, with a community trying to help. Now it's just a GitHub organization that hosts this repository (i'm trying to reuse the Discord server and the gitter/ms teams chats are just dead), without the people in the org actually participating in the project. Also, the itchy-api server which powers half of this app is on your personal profile.

**Comment by micahlt** [comment]
Merging this now.

**Comment by Semisol** [comment]
ok

**Comment by locness3** [comment]
I guess we can release 0.6.0?

**Pull request merged**
