### PR TITLE
Design improvements, loves, and favorites

### PR DESCRIPTION
**Pull request by micahlt**
An overview of this PR:
- Avoids using the [`micahlt/itchy-api`](https://github.com/micahlt/itchy-api) server as a proxy for requests to Scratch as much as possible
- Replaces most Axios and `fetch` requests with the [Capacitor HTTP plugin](https://github.com/capacitor-community/http)
- Enables loves and favorites for projects
- Adds a warning that Itchy Search is still in beta
- Adds a button that enables a project to be opened in the default web browser
- Fixes non-decoded HTML char codes in the Messages tab
- Adds a fade effect to the right edge of the Explore tab
- Shrinks the size of project thumbnails on the Explore tab
- Version bump to 0.7.4

You can test this version of Itchy using the APK in the zip below:
**[0-7-4.zip](https://github.com/Scratch-Client-4/itchy-ionic/files/6842217/0-7-4.zip)**

### CODE REVIEW

**Comment by locness3** [comment]
0.7.4? Imo it's a pretty major release

Glad to see you're working on this again.

**Comment by micahlt** [comment]
> 0.7.4? Imo it's a pretty major release

That's fair.  I was going to bump up to 0.8.0 when I added studios, but do you think now is a more appropriate time?  Also, any other feedback before I merge?

> Glad to see you're working on this again.

Things have gotten kind of hectic with my job, plus I'm trying to find out where I'm going to college.  I'm trying to get this done before I graduate 😅

**Comment by locness3** [comment]
> do you think now is a more appropriate time

Many small improvements is better than a rushed major feature.

> Also, any other feedback before I merge?

Looking at it tomorrow (GMT+1).

**Comment by micahlt** [comment]
Awesome - thanks a lot!

**Comment by locness3** [comment]
Looks good overall!

I'd use some blinking placeholders for when a project is loading though, instead of the "loading... :D". 

Also the text in the FAB on the project page is not legible in light mode :



(This screenshot uses an unshared project, opened from the My stuff page on the website; handling of those could be improved)

**Comment by locness3** [comment]
Also, using "open your profile" in the settings loads https://scratch.mit.edu/users/undefined 's profile :p

**Comment by micahlt** [comment]
Cool, thank you!  I'll fix the major issues related to the features in this PR (blinking placeholders is just a design thing that could take a while) and merge.

**Pull request merged**
