### PR TITLE
[WIP] Some internal improvements

### PR DESCRIPTION
**Pull request by locness3**
- Should I rather use `*Tab` than `*Page` ?
- @micahlt please explain what the matchRegexes function (defined differently in utils.js and SearchPage.vue) is all about

### CODE REVIEW

**Comment by locness3** [comment]
I don't know where the git conflicts come from.

**Comment by micahlt** [comment]
I know the issue - I've been working on adding messages for the last two days.  You've been working on this for the last two days.  That's why we have conflicts.  If you'd like I can attempt to manually merge this (e.g., just look at your changes, make them on my PC, and attribute them to you).

**Comment by micahlt** [comment]
> * @micahlt please explain what the matchRegexes function (defined differently in utils.js and SearchPage.vue) is all about

`matchesRegex()` is a function to determine what kind of URL a link is.  It returns an object with the type of link and the id if applicable.

**Comment by locness3** [comment]
So this means you're working on the master branch? T-T

**Comment by locness3** [comment]
Or reset (force-push) master to an earlier state then merge

**Comment by locness3** [comment]
If you want to attribute commits to me, use the following email address to commit : `locness3@e.email`

**Comment by locness3** [comment]
> So this means you're working on the master branch? T-T

Without asking for any review. The contributing guide - which says to not do things on master - applies to everyone.

**Comment by micahlt** [comment]
@locness3 What contributing guide 😶 I don't want to reset master to an earlier stage!  I added message reading, which took forever.

**Comment by locness3** [comment]
You should've worked on a seperate branch! And make a PR to ask for review. I mean https://github.com/Scratch-Client-4/contributing

**Comment by locness3** [comment]
But okay, just " manually merge" as you say.

**Comment by locness3** [comment]
Or use git cli to resolve the merge conflicts.

**Comment by micahlt** [comment]
> You should've worked on a seperate branch! And make a PR to ask for review. I mean https://github.com/Scratch-Client-4/contributing

Ohhhh snap.  Sorry 😐 I'll just manually merge since I can't get the CLI to work right.

**Comment by micahlt** [comment]
Manually merged by 954fad0.

**Pull request closed without merging**
