### PR TITLE
Lots of UX changes + feed component

### PR DESCRIPTION
**Pull request by micahlt**
In this pull request: 

- Better messages
- Combined user, studio, and project search
- Feed (aka What's Happening) component for logged in users on the explore page
- Fixed stretched Itchy logo on auth modal
- Friendly timestamps for messages
- Much better UI for project pages
- Love and favorite projects for logged in users
- Unread indicators for messages

### CODE REVIEW

**Comment by micahlt** [comment]
@locness3 I'd really appreciate a review before I merge this, but if you're too busy everything appears to be fine on my end.

**Comment by locness3** [comment]
@micahlt do you have any apk? I mostly gave up on developement for this project and i don't have an available dev environement.

**Comment by micahlt** [comment]
> @micahlt do you have any apk? I mostly gave up on developement for this project and i don't have an available dev environement.

Yep - let me zip one up and upload it.

**Comment by micahlt** [comment]
Here's the APK inside a zip (GitHub doesn't let me upload straight APK files).  

[0-8-7.zip](https://github.com/Scratch-Client-4/itchy-ionic/files/7273414/0-8-7.zip)

**Comment by locness3** [comment]
- Explore page is stuck on infinite loading for me.
- A list with square rounded pictures is IMO not suitable for searching for projects. Thumbnails like on the Explore page should be used (and searching for users/projects/studios should be seperated).
- Pressing system back button on the project page closes the app (i think that's related to the fact we use modals? #6)
- IMO, Feed deserves its own tab with more listed items

**Comment by locness3** [comment]
Also, no way to mark messages as read.

**Comment by micahlt** [comment]
> - Explore page is stuck on infinite loading when signed out, for me.

Same problem - thanks for investigating!

> - A list with square rounded pictures is IMO not suitable for searching for projects. Thumbnails like on the Explore page should be used (and searching for users/projects/studios should be seperated). 

So just remove the border radius?

> - Pressing system back button on the project page closes the app (i think that's related to the fact we use modals? #6)

That is an issue, but not related to this PR.  

> - IMO, Feed deserves its own tab with more listed items

I agree, but again that's a feature that needs to be added later on.

> Also, no way to mark messages as read.

Another feature coming soon.

**Comment by locness3** [comment]
> So just remove the border radius?

Well, no :

> Thumbnails like on the Explore page should be used (and searching for users/projects/studios should be seperated).

i.e. a Scratch project search shouldn't look like Contacts app

**Comment by micahlt** [comment]
> i.e. a Scratch project search shouldn't look like the Contacts app

Ah, I see - okay.  Well, that's a much harder thing to do since the `ProjectThumbnail` (I think that's what I named it) component doesn't take screen width into account.  For now, this search will have to do and I'll work on the UI later.

**Comment by micahlt** [comment]
All right, everything is working now.  Merging!

**Pull request merged**
